/*
* This file was generated by tools/stm32_clock_gen.sh on Mon 19 Jul 2021 12:56:49 PM EDT
*/

#if (PLLN == 192) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (193)
#  endif
# endif
#endif // PLLN == 192

#if (PLLN == 193) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (194)
#  endif
# endif
#endif // PLLN == 193

#if (PLLN == 194) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (195)
#  endif
# endif
#endif // PLLN == 194

#if (PLLN == 195) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (196)
#  endif
# endif
#endif // PLLN == 195

#if (PLLN == 196) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (197)
#  endif
# endif
#endif // PLLN == 196

#if (PLLN == 197) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (198)
#  endif
# endif
#endif // PLLN == 197

#if (PLLN == 198) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (199)
#  endif
# endif
#endif // PLLN == 198

#if (PLLN == 199) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (200)
#  endif
# endif
#endif // PLLN == 199

#if (PLLN == 200) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (201)
#  endif
# endif
#endif // PLLN == 200

#if (PLLN == 201) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (202)
#  endif
# endif
#endif // PLLN == 201

#if (PLLN == 202) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (203)
#  endif
# endif
#endif // PLLN == 202

#if (PLLN == 203) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (204)
#  endif
# endif
#endif // PLLN == 203

#if (PLLN == 204) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (205)
#  endif
# endif
#endif // PLLN == 204

#if (PLLN == 205) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (206)
#  endif
# endif
#endif // PLLN == 205

#if (PLLN == 206) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (207)
#  endif
# endif
#endif // PLLN == 206

#if (PLLN == 207) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (208)
#  endif
# endif
#endif // PLLN == 207

#if (PLLN == 208) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (209)
#  endif
# endif
#endif // PLLN == 208

#if (PLLN == 209) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (210)
#  endif
# endif
#endif // PLLN == 209

#if (PLLN == 210) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (211)
#  endif
# endif
#endif // PLLN == 210

#if (PLLN == 211) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (212)
#  endif
# endif
#endif // PLLN == 211

#if (PLLN == 212) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (213)
#  endif
# endif
#endif // PLLN == 212

#if (PLLN == 213) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (214)
#  endif
# endif
#endif // PLLN == 213

#if (PLLN == 214) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (215)
#  endif
# endif
#endif // PLLN == 214

#if (PLLN == 215) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (216)
#  endif
# endif
#endif // PLLN == 215

#if (PLLN == 216) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (217)
#  endif
# endif
#endif // PLLN == 216

#if (PLLN == 217) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (218)
#  endif
# endif
#endif // PLLN == 217

#if (PLLN == 218) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (219)
#  endif
# endif
#endif // PLLN == 218

#if (PLLN == 219) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (220)
#  endif
# endif
#endif // PLLN == 219

#if (PLLN == 220) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (221)
#  endif
# endif
#endif // PLLN == 220

#if (PLLN == 221) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (222)
#  endif
# endif
#endif // PLLN == 221

#if (PLLN == 222) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (223)
#  endif
# endif
#endif // PLLN == 222

#if (PLLN == 223) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (224)
#  endif
# endif
#endif // PLLN == 223

#if (PLLN == 224) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (225)
#  endif
# endif
#endif // PLLN == 224

#if (PLLN == 225) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (226)
#  endif
# endif
#endif // PLLN == 225

#if (PLLN == 226) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (227)
#  endif
# endif
#endif // PLLN == 226

#if (PLLN == 227) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (228)
#  endif
# endif
#endif // PLLN == 227

#if (PLLN == 228) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (229)
#  endif
# endif
#endif // PLLN == 228

#if (PLLN == 229) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (230)
#  endif
# endif
#endif // PLLN == 229

#if (PLLN == 230) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (231)
#  endif
# endif
#endif // PLLN == 230

#if (PLLN == 231) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (232)
#  endif
# endif
#endif // PLLN == 231

#if (PLLN == 232) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (233)
#  endif
# endif
#endif // PLLN == 232

#if (PLLN == 233) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (234)
#  endif
# endif
#endif // PLLN == 233

#if (PLLN == 234) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (235)
#  endif
# endif
#endif // PLLN == 234

#if (PLLN == 235) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (236)
#  endif
# endif
#endif // PLLN == 235

#if (PLLN == 236) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (237)
#  endif
# endif
#endif // PLLN == 236

#if (PLLN == 237) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (238)
#  endif
# endif
#endif // PLLN == 237

#if (PLLN == 238) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (239)
#  endif
# endif
#endif // PLLN == 238

#if (PLLN == 239) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (240)
#  endif
# endif
#endif // PLLN == 239

#if (PLLN == 240) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (241)
#  endif
# endif
#endif // PLLN == 240

#if (PLLN == 241) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (242)
#  endif
# endif
#endif // PLLN == 241

#if (PLLN == 242) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (243)
#  endif
# endif
#endif // PLLN == 242

#if (PLLN == 243) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (244)
#  endif
# endif
#endif // PLLN == 243

#if (PLLN == 244) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (245)
#  endif
# endif
#endif // PLLN == 244

#if (PLLN == 245) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (246)
#  endif
# endif
#endif // PLLN == 245

#if (PLLN == 246) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (247)
#  endif
# endif
#endif // PLLN == 246

#if (PLLN == 247) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (248)
#  endif
# endif
#endif // PLLN == 247

#if (PLLN == 248) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (249)
#  endif
# endif
#endif // PLLN == 248

#if (PLLN == 249) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (250)
#  endif
# endif
#endif // PLLN == 249

#if (PLLN == 250) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (251)
#  endif
# endif
#endif // PLLN == 250

#if (PLLN == 251) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (252)
#  endif
# endif
#endif // PLLN == 251

#if (PLLN == 252) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (253)
#  endif
# endif
#endif // PLLN == 252

#if (PLLN == 253) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (254)
#  endif
# endif
#endif // PLLN == 253

#if (PLLN == 254) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (255)
#  endif
# endif
#endif // PLLN == 254

#if (PLLN == 255) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (256)
#  endif
# endif
#endif // PLLN == 255

#if (PLLN == 256) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (257)
#  endif
# endif
#endif // PLLN == 256

#if (PLLN == 257) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (258)
#  endif
# endif
#endif // PLLN == 257

#if (PLLN == 258) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (259)
#  endif
# endif
#endif // PLLN == 258

#if (PLLN == 259) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (260)
#  endif
# endif
#endif // PLLN == 259

#if (PLLN == 260) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (261)
#  endif
# endif
#endif // PLLN == 260

#if (PLLN == 261) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (262)
#  endif
# endif
#endif // PLLN == 261

#if (PLLN == 262) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (263)
#  endif
# endif
#endif // PLLN == 262

#if (PLLN == 263) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (264)
#  endif
# endif
#endif // PLLN == 263

#if (PLLN == 264) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (265)
#  endif
# endif
#endif // PLLN == 264

#if (PLLN == 265) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (266)
#  endif
# endif
#endif // PLLN == 265

#if (PLLN == 266) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (267)
#  endif
# endif
#endif // PLLN == 266

#if (PLLN == 267) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (268)
#  endif
# endif
#endif // PLLN == 267

#if (PLLN == 268) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (269)
#  endif
# endif
#endif // PLLN == 268

#if (PLLN == 269) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (270)
#  endif
# endif
#endif // PLLN == 269

#if (PLLN == 270) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (271)
#  endif
# endif
#endif // PLLN == 270

#if (PLLN == 271) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (272)
#  endif
# endif
#endif // PLLN == 271

#if (PLLN == 272) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (273)
#  endif
# endif
#endif // PLLN == 272

#if (PLLN == 273) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (274)
#  endif
# endif
#endif // PLLN == 273

#if (PLLN == 274) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (275)
#  endif
# endif
#endif // PLLN == 274

#if (PLLN == 275) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (276)
#  endif
# endif
#endif // PLLN == 275

#if (PLLN == 276) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (277)
#  endif
# endif
#endif // PLLN == 276

#if (PLLN == 277) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (278)
#  endif
# endif
#endif // PLLN == 277

#if (PLLN == 278) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (279)
#  endif
# endif
#endif // PLLN == 278

#if (PLLN == 279) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (280)
#  endif
# endif
#endif // PLLN == 279

#if (PLLN == 280) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (281)
#  endif
# endif
#endif // PLLN == 280

#if (PLLN == 281) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (282)
#  endif
# endif
#endif // PLLN == 281

#if (PLLN == 282) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (283)
#  endif
# endif
#endif // PLLN == 282

#if (PLLN == 283) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (284)
#  endif
# endif
#endif // PLLN == 283

#if (PLLN == 284) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (285)
#  endif
# endif
#endif // PLLN == 284

#if (PLLN == 285) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (286)
#  endif
# endif
#endif // PLLN == 285

#if (PLLN == 286) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (287)
#  endif
# endif
#endif // PLLN == 286

#if (PLLN == 287) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (288)
#  endif
# endif
#endif // PLLN == 287

#if (PLLN == 288) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (289)
#  endif
# endif
#endif // PLLN == 288

#if (PLLN == 289) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (290)
#  endif
# endif
#endif // PLLN == 289

#if (PLLN == 290) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (291)
#  endif
# endif
#endif // PLLN == 290

#if (PLLN == 291) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (292)
#  endif
# endif
#endif // PLLN == 291

#if (PLLN == 292) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (293)
#  endif
# endif
#endif // PLLN == 292

#if (PLLN == 293) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (294)
#  endif
# endif
#endif // PLLN == 293

#if (PLLN == 294) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (295)
#  endif
# endif
#endif // PLLN == 294

#if (PLLN == 295) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (296)
#  endif
# endif
#endif // PLLN == 295

#if (PLLN == 296) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (297)
#  endif
# endif
#endif // PLLN == 296

#if (PLLN == 297) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (298)
#  endif
# endif
#endif // PLLN == 297

#if (PLLN == 298) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (299)
#  endif
# endif
#endif // PLLN == 298

#if (PLLN == 299) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (300)
#  endif
# endif
#endif // PLLN == 299

#if (PLLN == 300) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (301)
#  endif
# endif
#endif // PLLN == 300

#if (PLLN == 301) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (302)
#  endif
# endif
#endif // PLLN == 301

#if (PLLN == 302) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (303)
#  endif
# endif
#endif // PLLN == 302

#if (PLLN == 303) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (304)
#  endif
# endif
#endif // PLLN == 303

#if (PLLN == 304) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (305)
#  endif
# endif
#endif // PLLN == 304

#if (PLLN == 305) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (306)
#  endif
# endif
#endif // PLLN == 305

#if (PLLN == 306) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (307)
#  endif
# endif
#endif // PLLN == 306

#if (PLLN == 307) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (308)
#  endif
# endif
#endif // PLLN == 307

#if (PLLN == 308) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (309)
#  endif
# endif
#endif // PLLN == 308

#if (PLLN == 309) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (310)
#  endif
# endif
#endif // PLLN == 309

#if (PLLN == 310) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (311)
#  endif
# endif
#endif // PLLN == 310

#if (PLLN == 311) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (312)
#  endif
# endif
#endif // PLLN == 311

#if (PLLN == 312) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (313)
#  endif
# endif
#endif // PLLN == 312

#if (PLLN == 313) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (314)
#  endif
# endif
#endif // PLLN == 313

#if (PLLN == 314) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (315)
#  endif
# endif
#endif // PLLN == 314

#if (PLLN == 315) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (316)
#  endif
# endif
#endif // PLLN == 315

#if (PLLN == 316) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (317)
#  endif
# endif
#endif // PLLN == 316

#if (PLLN == 317) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (318)
#  endif
# endif
#endif // PLLN == 317

#if (PLLN == 318) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (319)
#  endif
# endif
#endif // PLLN == 318

#if (PLLN == 319) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (320)
#  endif
# endif
#endif // PLLN == 319

#if (PLLN == 320) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (321)
#  endif
# endif
#endif // PLLN == 320

#if (PLLN == 321) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (322)
#  endif
# endif
#endif // PLLN == 321

#if (PLLN == 322) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (323)
#  endif
# endif
#endif // PLLN == 322

#if (PLLN == 323) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (324)
#  endif
# endif
#endif // PLLN == 323

#if (PLLN == 324) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (325)
#  endif
# endif
#endif // PLLN == 324

#if (PLLN == 325) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (326)
#  endif
# endif
#endif // PLLN == 325

#if (PLLN == 326) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (327)
#  endif
# endif
#endif // PLLN == 326

#if (PLLN == 327) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (328)
#  endif
# endif
#endif // PLLN == 327

#if (PLLN == 328) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (329)
#  endif
# endif
#endif // PLLN == 328

#if (PLLN == 329) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (330)
#  endif
# endif
#endif // PLLN == 329

#if (PLLN == 330) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (331)
#  endif
# endif
#endif // PLLN == 330

#if (PLLN == 331) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (332)
#  endif
# endif
#endif // PLLN == 331

#if (PLLN == 332) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (333)
#  endif
# endif
#endif // PLLN == 332

#if (PLLN == 333) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (334)
#  endif
# endif
#endif // PLLN == 333

#if (PLLN == 334) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (335)
#  endif
# endif
#endif // PLLN == 334

#if (PLLN == 335) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (336)
#  endif
# endif
#endif // PLLN == 335

#if (PLLN == 336) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (337)
#  endif
# endif
#endif // PLLN == 336

#if (PLLN == 337) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (338)
#  endif
# endif
#endif // PLLN == 337

#if (PLLN == 338) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (339)
#  endif
# endif
#endif // PLLN == 338

#if (PLLN == 339) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (340)
#  endif
# endif
#endif // PLLN == 339

#if (PLLN == 340) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (341)
#  endif
# endif
#endif // PLLN == 340

#if (PLLN == 341) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (342)
#  endif
# endif
#endif // PLLN == 341

#if (PLLN == 342) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (343)
#  endif
# endif
#endif // PLLN == 342

#if (PLLN == 343) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (344)
#  endif
# endif
#endif // PLLN == 343

#if (PLLN == 344) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (345)
#  endif
# endif
#endif // PLLN == 344

#if (PLLN == 345) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (346)
#  endif
# endif
#endif // PLLN == 345

#if (PLLN == 346) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (347)
#  endif
# endif
#endif // PLLN == 346

#if (PLLN == 347) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (348)
#  endif
# endif
#endif // PLLN == 347

#if (PLLN == 348) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (349)
#  endif
# endif
#endif // PLLN == 348

#if (PLLN == 349) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (350)
#  endif
# endif
#endif // PLLN == 349

#if (PLLN == 350) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (351)
#  endif
# endif
#endif // PLLN == 350

#if (PLLN == 351) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (352)
#  endif
# endif
#endif // PLLN == 351

#if (PLLN == 352) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (353)
#  endif
# endif
#endif // PLLN == 352

#if (PLLN == 353) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (354)
#  endif
# endif
#endif // PLLN == 353

#if (PLLN == 354) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (355)
#  endif
# endif
#endif // PLLN == 354

#if (PLLN == 355) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (356)
#  endif
# endif
#endif // PLLN == 355

#if (PLLN == 356) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (357)
#  endif
# endif
#endif // PLLN == 356

#if (PLLN == 357) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (358)
#  endif
# endif
#endif // PLLN == 357

#if (PLLN == 358) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (359)
#  endif
# endif
#endif // PLLN == 358

#if (PLLN == 359) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (360)
#  endif
# endif
#endif // PLLN == 359

#if (PLLN == 360) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (361)
#  endif
# endif
#endif // PLLN == 360

#if (PLLN == 361) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (362)
#  endif
# endif
#endif // PLLN == 361

#if (PLLN == 362) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (363)
#  endif
# endif
#endif // PLLN == 362

#if (PLLN == 363) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (364)
#  endif
# endif
#endif // PLLN == 363

#if (PLLN == 364) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (365)
#  endif
# endif
#endif // PLLN == 364

#if (PLLN == 365) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (366)
#  endif
# endif
#endif // PLLN == 365

#if (PLLN == 366) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (367)
#  endif
# endif
#endif // PLLN == 366

#if (PLLN == 367) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (368)
#  endif
# endif
#endif // PLLN == 367

#if (PLLN == 368) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (369)
#  endif
# endif
#endif // PLLN == 368

#if (PLLN == 369) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (370)
#  endif
# endif
#endif // PLLN == 369

#if (PLLN == 370) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (371)
#  endif
# endif
#endif // PLLN == 370

#if (PLLN == 371) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (372)
#  endif
# endif
#endif // PLLN == 371

#if (PLLN == 372) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (373)
#  endif
# endif
#endif // PLLN == 372

#if (PLLN == 373) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (374)
#  endif
# endif
#endif // PLLN == 373

#if (PLLN == 374) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (375)
#  endif
# endif
#endif // PLLN == 374

#if (PLLN == 375) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (376)
#  endif
# endif
#endif // PLLN == 375

#if (PLLN == 376) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (377)
#  endif
# endif
#endif // PLLN == 376

#if (PLLN == 377) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (378)
#  endif
# endif
#endif // PLLN == 377

#if (PLLN == 378) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (379)
#  endif
# endif
#endif // PLLN == 378

#if (PLLN == 379) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (380)
#  endif
# endif
#endif // PLLN == 379

#if (PLLN == 380) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (381)
#  endif
# endif
#endif // PLLN == 380

#if (PLLN == 381) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (382)
#  endif
# endif
#endif // PLLN == 381

#if (PLLN == 382) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (383)
#  endif
# endif
#endif // PLLN == 382

#if (PLLN == 383) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (384)
#  endif
# endif
#endif // PLLN == 383

#if (PLLN == 384) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (385)
#  endif
# endif
#endif // PLLN == 384

#if (PLLN == 385) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (386)
#  endif
# endif
#endif // PLLN == 385

#if (PLLN == 386) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (387)
#  endif
# endif
#endif // PLLN == 386

#if (PLLN == 387) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (388)
#  endif
# endif
#endif // PLLN == 387

#if (PLLN == 388) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (389)
#  endif
# endif
#endif // PLLN == 388

#if (PLLN == 389) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (390)
#  endif
# endif
#endif // PLLN == 389

#if (PLLN == 390) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (391)
#  endif
# endif
#endif // PLLN == 390

#if (PLLN == 391) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (392)
#  endif
# endif
#endif // PLLN == 391

#if (PLLN == 392) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (393)
#  endif
# endif
#endif // PLLN == 392

#if (PLLN == 393) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (394)
#  endif
# endif
#endif // PLLN == 393

#if (PLLN == 394) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (395)
#  endif
# endif
#endif // PLLN == 394

#if (PLLN == 395) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (396)
#  endif
# endif
#endif // PLLN == 395

#if (PLLN == 396) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (397)
#  endif
# endif
#endif // PLLN == 396

#if (PLLN == 397) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (398)
#  endif
# endif
#endif // PLLN == 397

#if (PLLN == 398) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (399)
#  endif
# endif
#endif // PLLN == 398

#if (PLLN == 399) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (400)
#  endif
# endif
#endif // PLLN == 399

#if (PLLN == 400) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (401)
#  endif
# endif
#endif // PLLN == 400

#if (PLLN == 401) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (402)
#  endif
# endif
#endif // PLLN == 401

#if (PLLN == 402) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (403)
#  endif
# endif
#endif // PLLN == 402

#if (PLLN == 403) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (404)
#  endif
# endif
#endif // PLLN == 403

#if (PLLN == 404) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (405)
#  endif
# endif
#endif // PLLN == 404

#if (PLLN == 405) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (406)
#  endif
# endif
#endif // PLLN == 405

#if (PLLN == 406) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (407)
#  endif
# endif
#endif // PLLN == 406

#if (PLLN == 407) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (408)
#  endif
# endif
#endif // PLLN == 407

#if (PLLN == 408) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (409)
#  endif
# endif
#endif // PLLN == 408

#if (PLLN == 409) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (410)
#  endif
# endif
#endif // PLLN == 409

#if (PLLN == 410) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (411)
#  endif
# endif
#endif // PLLN == 410

#if (PLLN == 411) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (412)
#  endif
# endif
#endif // PLLN == 411

#if (PLLN == 412) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (413)
#  endif
# endif
#endif // PLLN == 412

#if (PLLN == 413) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (414)
#  endif
# endif
#endif // PLLN == 413

#if (PLLN == 414) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (415)
#  endif
# endif
#endif // PLLN == 414

#if (PLLN == 415) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (416)
#  endif
# endif
#endif // PLLN == 415

#if (PLLN == 416) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (417)
#  endif
# endif
#endif // PLLN == 416

#if (PLLN == 417) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (418)
#  endif
# endif
#endif // PLLN == 417

#if (PLLN == 418) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (419)
#  endif
# endif
#endif // PLLN == 418

#if (PLLN == 419) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (420)
#  endif
# endif
#endif // PLLN == 419

#if (PLLN == 420) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (421)
#  endif
# endif
#endif // PLLN == 420

#if (PLLN == 421) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (422)
#  endif
# endif
#endif // PLLN == 421

#if (PLLN == 422) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (423)
#  endif
# endif
#endif // PLLN == 422

#if (PLLN == 423) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (424)
#  endif
# endif
#endif // PLLN == 423

#if (PLLN == 424) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (425)
#  endif
# endif
#endif // PLLN == 424

#if (PLLN == 425) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (426)
#  endif
# endif
#endif // PLLN == 425

#if (PLLN == 426) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (427)
#  endif
# endif
#endif // PLLN == 426

#if (PLLN == 427) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (428)
#  endif
# endif
#endif // PLLN == 427

#if (PLLN == 428) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (429)
#  endif
# endif
#endif // PLLN == 428

#if (PLLN == 429) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (430)
#  endif
# endif
#endif // PLLN == 429

#if (PLLN == 430) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (431)
#  endif
# endif
#endif // PLLN == 430

#if (PLLN == 431) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (432)
#  endif
# endif
#endif // PLLN == 431

#if (PLLN == 432) && (!defined(PLLP_DIV)) && (PLLN <= PLLN_MAX)
# undef  VCO_OUTPUT_HZ
# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
# if VCO_OUTPUT_HZ > VCO_OUTPUT_MAX_HZ
#  undef  PLLN
#  define PLLN (PLLN_MAX + 1)
# else
#  include "system_PLL_STM32Fx_2.h"
#  if ! defined(PLLP_DIV)
#   undef  PLLN
#   define PLLN (433)
#  endif
# endif
#endif // PLLN == 432

